### ISSUE TITLE
Changing trace type after opening an experiment does not update the experiment

### ISSUE THREAD

**Issue by arfio** [eclipse-tracecompass/org.eclipse.tracecompass#110]
To reproduce the issue:
- Open a trace with type 1
- Create an experiment with this trace
- Change the trace type of the trace to type 2 in the "traces" folder and not in the experiment

The trace in the experiment will display the icon of the type 2 but the trace will still be parsed in the experiment as a type 1.
The issue does not appear when changing the trace directly in the experiment.

The trace in the experiment should keep the icon the type 1.

**Comment by bhufmann** [comment]
I'm not able to reproduce this error. Changing the trace type of a trace from the traces folder or under the experiment will propagate the change to the trace under the traces folder and all experiments where this trace is part of. It just not changes the icon of the trace (in traces folder and under each experiment) but also changes the persistent property on the trace, that is used when creating the trace instance.

I tested that with a LTTng UST trace.

- Open a trace with type1 (LTTng UST trace type)
- Create an experiment with this trace
- Change the trace type of the trace to type 2 (Generic CTF)  in the "traces" folder and not in the experiment

The icon changes everywhere and only views applicable to Generic CTF traces are shown under the Views folder.

> The Trace in the experiment should keep the icon the type 1

No, the trace in the experiment and trace under the traces folder are the same trace. Changes to the settings (trace type) need to be propagated. If you want to have a different trace type used in the experiment, then you have to copy the trace first and then add the copied trace to the experiment

**Comment by arfio** [comment]
I cannot reproduce this issue anymore.
