### ISSUE TITLE
Cannot import a ftrace file(raw ascii nor trace-cmd)

### ISSUE THREAD

**Issue by gyulkkajo** [eclipse-tracecompass/org.eclipse.tracecompass#124]
Hi,

I tried to open a ftrace log but trace-compass cannot open it without any error. I tried to set a type manually then it show below error.

<img width="721" alt="image" src="https://github.com/user-attachments/assets/49cf8886-9a2c-4d54-923e-5ead5f5cbfe3">

I've tried several version of tracecompass and other platform (linux and mac) but none of these works.

Could you check this?

Thanks

**Comment by gyulkkajo** [comment]
I'd like to add one that the "trace.dat" file is valid and can be opened on kernelshark.

**Comment by bhufmann** [comment]
Do you have the ftrace trace-type installed? If not, use menu `Tools -> Add-ons...`. A new dialog will open. Search for `ftrace`. Then select checkbox `Trace Compass ftrace (Incubation)` and click on finish `Finish`. Click on `Next` on new dialogs and accept the license agreement and finally click `Finish` again. Restart Trace Compass when asked. This will add the ftrace parser. Now you will be able to select the trace type of an existing trace file in the workspace by using right-mouse click on trace `Select Trace Type` -> `Ftrace Format` -> `Binary Ftrace`. If the file is a converted to textual ftrace then use `Raw Textual Ftrace` instead. 

If you open a new trace or import a new trace to the workspace, the trace type should be detected automatically.

**Comment by gyulkkajo** [comment]
Appreciated @bhufmann. Previously I remember that I saw the traces without installing any plugins but looks like it changed.
Thanks!
