### ISSUE TITLE
Fix markdown formatting in API_POLICY

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-tracecompass/org.eclipse.tracecompass#5]
It doesn't render well.

Picture to illustrate issue.
![image](https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/assets/419535/f274f6ad-8cec-4cf2-9647-1ffc5d3b42f9)

**Comment by BDFL669** [comment]
I would really love to work on this issue if I could kindly be assigned

**Comment by bhufmann** [comment]
> I would really love to work on this issue if I could kindly be assigned
@BDFL669 Thanks for offering. I have already submitted a PR.
