### ISSUE TITLE
Incubator is broken on Windows?

### ISSUE THREAD

**Issue by DavidA2014** [eclipse-tracecompass/org.eclipse.tracecompass#83]
Running TraceCompass 9.3.0 on Windows 11.

**Help > Check for Updates** gives:

![image](https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/assets/7724321/1f930613-4b78-45cf-a7d3-1967d8843e2f)

Maybe a proxy issue?

**Comment by MatthewKhouzam** [comment]
Try going to window->Network?
![Screenshot from 2024-05-16 13-22-49](https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/assets/419535/eeaa8401-0c12-4ea6-ac12-7335e8c6e241)


Let's get the easy things out of the way first?

**Comment by DavidA2014** [comment]
Thanks for your help. **Help > Install New Software...** is now working, without a proxy setting.

I did have to specify site:

**https://download.eclipse.org/tracecompass.incubator/master/repository/**

as you suggested.

**Comment by MatthewKhouzam** [comment]
David, I would love to. Please send me contact info directly to my email address, and we can move forward from there.
